import overpy
import json
import time
import glob

api = overpy.Overpass()
path = './place_ele/'
required = list(range(-180, 180))

for i in required:
    tic = time.time()

    print(i)

    if path + str(i) + '.geojson' in glob.glob(path + '*.geojson'):
        print('already present...')
        continue

    result = api.query('''/*
        This has been generated by the overpass-turbo wizard.
        The original search was:
        “place=* and ele=*”
        */
        [out:json][timeout:120];
        // gather results
        (
            // query part for: “place=* and ele=*”
            node["place"]["ele"](-89,%f,89,%f);
        );
        // print results
        out body;
        >;
        out skel qt;''' % (i, i + 1))

    duration = time.time() - tic
    print('Got %i features in %1.1f s' % (len(result.nodes), duration))

    features = []
    for node in result.nodes:
        properties = {
            'ele': str(node.tags.get('ele'))
        }
        feature = {
            'type': 'Feature',
            'properties': properties,
            'geometry': {
                'type': 'Point',
                'coordinates': [float(node.lon), float(node.lat)]
            },
            'id': 'node/' + str(node.id)
        }
        features += [feature]

    geojson = {
        'type': 'FeatureCollection',
        'features': features
    }

    with open(path + '%i.geojson' % i, 'w') as f:
        json.dump(geojson, f)

    time_sleep = max(60, 2 * duration)
    print('start sleep for %1.0f s...' % time_sleep)
    time.sleep(time_sleep)
    print('continue...')
